---
- name:
  hosts: all
  roles:
    - role: base
      tags: [base]
    - role: locale
      tags: [locale]
    - role: ntp
      tags: [ntp]
    - role: build-essential
      tags: [utils]
    - role: weareinteractive.ufw
      when: ansible_facts['os_family'] == 'Debian'
      tags: [firewall]
    - role: pfw
      when: ansible_facts['os_family'] == 'FreeBSD'
      tags: [firewall]
    - role: applications
      tags: [applications]
    - role: openbox
      tags: [openbox]
    - role: xdm
      tags: [xdm]
  vars_files:
    - vars/playbook.yml
