---
- name:
  hosts: all
  roles:
    - role: base
      tags: [base]
    - role: ANXS.hostname
      tags: [hostname]
    - role: Stouts.locale
      tags: [locale]
    - role: ANXS.utilities
      tags: [utils]
    - role: ANXS.ntp
      tags: [ntp]
    - role: ANXS.build-essential
      tags: [utils]
    - role: franklinkim.ufw
      tags: [firewall]
    - role: proprietary
      tags: [proprietary]
    - role: applications
      tags: [applications]
    - role: openbox
      tags: [openbox]
    - role: xdm
      tags: [xdm]
  vars_files:
    - vars/playbook.yml
