---
- name: install packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ xdm.packages }}"

# TODO: make this optional based on system if supporting older Debian systems
- include: systemd.yml