---
defaults:
  password: $6$6J3nXIJ4xZg7$RayRiuVr4oV20PBFkz7O9dKo0rzFeml6c2WWHGhYvV8cbikbnKr0MEDoGfQlF01ZOD/0HwsJBzO2/Iia2UVbf.
users:
  - username: vagrant
    shell: /bin/bash
    name: Vagrant
    sudoer: true
