---
display:
  dpi: 96
  scaling:
    gdk_scale: 1
    gdk_dpi_scale: 1
    qt_auto_screen_scale_factor: 0
defaults:
  password: $6$6J3nXIJ4xZg7$RayRiuVr4oV20PBFkz7O9dKo0rzFeml6c2WWHGhYvV8cbikbnKr0MEDoGfQlF01ZOD/0HwsJBzO2/Iia2UVbf.
  dirs:
    tmp: /tmp
    # ensure any override ends with /
    resources: resources/
    app: /usr/local/apps
users: []
partitions:
  - path: /
network_devices:
  - eth0
locale:
  install_locales:
    - en_IE.UTF-8
  charset: UTF-8
  lang: en_IE.UTF-8