---
base:
  extra_paths:
    - /snap/bin
  packages:
    - name: git
    - name: python3-pip
    - name: pipx
    - name: pkgconf
    - name: openjdk-17-jdk
    - name: flatpak
    - name: bash-completion
    - name: isc-dhcp-server
