---
- name: add repository keys
  apt_key: state=present
           {% if item.url is defined %}
           url={{ item.url }}
           {% endif %}
  with_items: "{{ applications.repositories }}"

- name: add repositories
  apt_repository: repo='{{ item.entry }}' update_cache=yes
  with_items: "{{ applications.repositories }}"

- include: package.yml
  with_items: "{{ applications.packages }}"

- include: package.yml
  with_items: "{{ applications.user_packages }}"

- include: user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: cur_user
