---
- name: add repository keys
  apt_key: state=present url={{ item.url }}
  when: item.url is defined
  with_items: "{{ applications.repositories }}"

- name: add repositories
  apt_repository: repo='{{ item.entry }}' update_cache=yes
  with_items: "{{ applications.repositories }}"

- include: package.yml
  with_items: "{{ applications.packages }}"

- include: package.yml
  with_items: "{{ applications.user_packages }}"
