---
- name: add repository keys
  apt_key: state=present
           {% if item.url is defined %}
           url={{ item.url }}
           {% endif %}
  with_items: "{{ applications.repositories }}"

- name: add repositories
  apt_repository: repo='{{ item.entry }}' update_cache=yes
  with_items: "{{ applications.repositories }}"

- include: package.yml
  with_items: "{{ application.packages }}"

- include: package.yml
  with_items: "{{ application.user_packages }}"