---
machine_type: generic
package_installer: precompiled
ufw_rules:
  - port: 80
    rule: allow
  - port: 443
    rule: allow
  - port: 8443
    rule: allow
  - port: 22
    rule: allow
  - from_ip: 127.0.0.1/8
    rule: allow