---
applications:
  repositories:
    - entry: ppa:agornostal/ulauncher
  packages:
    - name: firefox
    - name: ulauncher
      install_recommends: false
    - name: redshift-gtk
      install_recommends: false
    - name: clipit
    - name: geany
  snaps:
    - name: bitwarden
      desktop_source: /var/lib/snapd/desktop/applications/bitwarden_bitwarden.desktop
    - name: chromium
      desktop_source: /var/lib/snapd/desktop/applications/chromium_chromium.desktop

  user_packages: []
