---
applications:
  repositories:
    - entry: ppa:agornostal/ulauncher
  packages:
    - name: firefox
    - name: ulauncher
      install_recommends: false
    - name: redshift-gtk
      install_recommends: false
    - name: clipit
    - name: geany
  snaps:
    - name: bitwarden
      desktop_source: /snap/bitwarden/current/meta/gui/bitwarden.desktop
    - name: chromium
      desktop_source: /snap/chromium/current/meta/gui/chromium.desktop

  user_packages: []
