---
applications:
  repositories:
    - entry: deb https://deb.opera.com/opera-stable/ stable non-free
      url: https://deb.opera.com/archive.key
    - entry: deb http://repo.vivaldi.com/stable/deb/ stable main
      url: http://repo.vivaldi.com/stable/linux_signing_key.pub
  packages:
    - name: emacs24-nox
    - name: password-gorilla
    - name: firefox
    - name: chromium-browser
    - name: opera-stable
    - name: vivaldi-stable

  user_packages: []
