---
applications:
  repositories:
    - entry: deb http://repo.vivaldi.com/stable/deb/ stable main
      url: http://repo.vivaldi.com/stable/linux_signing_key.pub
    - entry: ppa:agornostal/ulauncher
  packages:
    - name: password-gorilla
    - name: firefox
    - name: chromium-browser
    - name: vivaldi-stable
    - name: ulauncher
    - name: redshift-gtk
    - name: clipit

  user_packages: []
