---
applications:
  repositories: []
  packages:
    - name: vlc
    - name: iceweasel
    - deb_name: ulauncher.deb
      url: https://github.com/Ulauncher/Ulauncher/releases/download/5.7.5/ulauncher_5.7.5_all.deb
      install_recommends: false
    - name: redshift-gtk
      install_recommends: false
    - name: clipit
    - name: geany
  flatpaks:
    - name: com.bitwarden.desktop

  user_packages: []
