---
applications:
  repositories: []
  packages:
    - name: vlc
    - deb_name: ulauncher.deb
      url: https://github.com/Ulauncher/Ulauncher/releases/download/5.7.5/ulauncher_5.7.5_all.deb
    - name: redshift-gtk
    - name: geoclue-2.0
    - name: geany
  flatpaks:
    - name: com.bitwarden.desktop
    - name: org.mozilla.firefox

  user_packages: []
