---
applications:
  linux:
    repositories: []
    packages:
      - name: vlc
      - pkg_name: ulauncher.deb
        url: https://github.com/Ulauncher/Ulauncher/releases/download/5.15.2/ulauncher_5.15.2_all.deb
      - name: redshift-gtk
      - name: geoclue-2.0
      - name: geany
    flatpaks:
      - name: com.bitwarden.desktop
      - name: org.mozilla.firefox
  freebsd:
    packages:
      - name: multimedia/vlc
        environment:
          # ffmpeg port needs this
          DISABLE_VULNERABILITIES: "yes"
      - name: multimedia/smplayer
      - name: accessibility/redshift
      - name: devel/geany
      - name: www/firefox

  user_packages: []
