---
- name: install Python packages
  community.general.pipx: name=autorandr version=1.1

- name: create default screenlayout
  become_user: "{{ cur_user.username }}"
  template: src=screenlayout.sh.j2 dest={{ home_dir }}/.screenlayout/default.sh
            mode=0755

# TODO: create a program that:
# 1) Parses currently configured xrandr output and saves as profile (autorandr does this)
# 2) Can detect which profiles are available currently (autorandr does this)
# 3) Can load profile on request (autorandr does this)
# 2) Allows user to specify order of priority of profiles for user
# 3) Loads the first matched profile in the priority list for the current user.
# 4) Can run as daemon that detects events from the X server (similar to https://bitbucket.org/portix/srandrd)
# 5) On new/removed display events, load the first matched profile
# https://github.com/nalipaz/poll-xrandr is a script that reruns autorandr as needed. See https://unix.stackexchange.com/a/190011
