---
- name: install base packages
  apt: name={{ openbox.base_packages }} state=present

- name: install device packages
  apt: name={{ openbox.device_packages }}
       state=present

- name: install python packages
  pip: "{{ item }}"
  with_items: "{{ openbox.pip_packages }}"

- name: copy static files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ openbox.static_files }}"

- name: create openbox scripts
  template: src={{ item }}.j2 dest=/usr/bin/{{ item }} mode=0755
  with_items:
    - oblogout

- name: create Debian menu
  shell: update-menus

- name: set alternatives
  shell: update-alternatives --set {{ item.command }} {{ item.executable }}
  with_items: "{{ openbox.alternatives }}"

- name: enable connman
  service: name=connman enabled=yes

- name: update networking config
  template:
    src: network_interfaces.j2
    dest: /etc/network/interfaces

- include: user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: cur_user
