---
- import_tasks: linux.yml
  when: os_target == 'linux'

- import_tasks: freebsd.yml
  when: os_target == 'freebsd'

- name: install python packages
  community.general.pipx:
    name: "{{ item }}"
  with_items: "{{ openbox.pipx_packages }}"

- name: copy static files
  copy:
    src: "{{ item.src }}"
    dest: "{% if item.directory is defined %}{{ openbox[os_target].directories[item.directory] }}/{% endif %}{{ item.dest }}"
  with_items: "{{ openbox.static_files }}"

- name: copy templated files
  template:
    src: "{{ item.src }}"
    dest: "{% if item.directory is defined %}{{ openbox[os_target].directories[item.directory] }}/{% endif %}{{ item.dest }}"
  with_items: "{{ openbox.templated_files }}"

- name: create openbox scripts
  template: src={{ item }}.j2 dest={{ openbox[os_target].directories.usr_bin }}/{{ item }} mode=0755
  with_items:
    - oblogout

- name: retrieve all standard usernames
  script:
    cmd: list_usernames.sh
  register: raw_usernames
- name: clean raw usernames into list
  set_fact:
    all_usernames: "{{ raw_usernames.stdout_lines|select|list }}"

- include_tasks: user.yml
  with_items: "{{ all_usernames }}"
  loop_control:
    loop_var: cur_username
