---
- name: install base packages
  apt: name={{ item }} state=present
  with_items: "{{ openbox.base_packages }}"

- name: install packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ openbox.packages }}"

- name: install device packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ openbox.device_packages }}"

- name: install python packages
  pip: "{{ item }}"
  with_items: "{{ openbox.pip_packages }}"

- name: create openbox scripts
  template: src={{ item }}.j2 dest=/usr/bin/{{ item }} mode=0755
  with_items:
    - oblogout

- name: create Debian menu
  shell: update-menus

- name: enable network manager
  service: name=network-manager enabled=yes

- name: update networking config
  template:
    src: network_interfaces.j2
    dest: /etc/network/interfaces

- include: user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: cur_user
