---
- name: install base packages
  apt: name={{ openbox.base_packages }} state=present

- name: install device packages
  apt: name={{ openbox.device_packages }}
       state=present

- name: install python packages
  community.general.pipx:
    name: "{{ item }}"
  with_items: "{{ openbox.pipx_packages }}"

- name: copy static files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ openbox.static_files }}"

- name: create openbox scripts
  template: src={{ item }}.j2 dest=/usr/bin/{{ item }} mode=0755
  with_items:
    - oblogout

- name: create Debian menu
  shell: update-menus

- name: set alternatives
  shell: "update-alternatives --{{ item.subcommand }} {{ item.link|default('') }}
          {{ item.name }} {{ item.executable }} {{ item.priority|default('') }}"
  with_items: "{{ openbox.alternatives }}"

- name: enable network manager
  service: name=NetworkManager enabled=yes

- name: retrieve all standard usernames
  script:
    cmd: list_usernames.sh
  register: raw_usernames
- name: clean raw usernames into list
  set_fact:
    all_usernames: "{{ raw_usernames.stdout_lines|select|list }}"

- include: user.yml
  with_items: "{{ all_usernames }}"
  loop_control:
    loop_var: cur_username
