---
- name: user-specific facts
  set_fact:
    home_dir: /home/{{ cur_user.username }}

- name: create config dirs
  become_user: "{{ cur_user.username }}"
  file: state=directory path={{ item }}
  with_items:
    - "{{ home_dir }}/.config/openbox"
    - "{{ home_dir }}/.config/conky"
    - "{{ home_dir }}/.config/tint2"
    - "{{ home_dir }}/.config/ulauncher"
    - "{{ home_dir }}/.config/carillon"
    - "{{ home_dir }}/.config/rox.sourceforge.net/MIME-types"

- name: create X init script
  become_user: "{{ cur_user.username }}"
  template: src=xinitrc.j2 dest={{ home_dir }}/.xinitrc mode=0744

- name: create ROX filer associations
  become_user: "{{ cur_user.username }}"
  template: src=rox_handler.sh.j2
            dest={{ home_dir }}/.config/rox.sourceforge.net/MIME-types/{{ item.output_file }}
            mode=0755
  with_items:
    - { command: feh, output_file: image_jpeg }
    - { command: feh, output_file: image_png }
    - { command: x-www-browser, output_file: text_html }
    - { command: x-www-browser, output_file: application_pdf }
    - { command: geany, output_file: text_plain }
    - { command: geany, output_file: application_json }

- name: create config files
  become_user: "{{ cur_user.username }}"
  template: src={{ item.file }}.j2 dest={{ home_dir }}/{{ item.dir }}/{{ item.output_file|default(item.file) }}
  with_items:
    - { file: xresources, dir: ".", output_file: .Xresources }
    - { file: xscreensaver, dir: ".", output_file: .xscreensaver }
    - { file: rc.xml, dir: .config/openbox }
    - { file: environment, dir: .config/openbox }
    - { file: menu.xml, dir: .config/openbox }
    - { file: autostart, dir: .config/openbox }
    - { file: conky.conf, dir: .config/conky }
    - { file: tint2rc, dir: .config/tint2 }
    - { file: ulauncher_settings.json, dir: .config/ulauncher, output_file: settings.json }
    - { file: carillon.yml, dir: .config/carillon, output_file: default.yml }

- name: copy resources
  become_user: "{{ cur_user.username }}"
  copy: src={{ defaults.dirs.resources }} dest={{ home_dir }}/resources
