---
- name: create directories if they don't exist
  file: path={{ defaults['dirs'][item] }} state=directory mode=0755
  with_items:
    - app

- name: set FreeBSD facts
  set_fact:
    os_target: freebsd
  when: ansible_facts['os_family'] == 'FreeBSD'

- name: set Linux facts
  set_fact:
    os_target: linux
  when: ansible_facts['os_family'] == 'Debian'