---
- name: create directories if they don't exist
  file: path={{ defaults['dirs'][item] }} state=directory mode=0755
  with_items:
    - app

- name: install ACPI if not already installed
  apt: name=acpid

- include: acpi_events.yml
  with_dict: "{{ machine.acpi_events }}"
  loop_control:
    loop_var: acpi_events
