---
openbox:
  xrandr_configuration: ""
  alternatives:
    - command: x-terminal-emulator
      executable: /usr/bin/urxvt
  keyboard:
    selected: en_gb
    layouts:
      en_gb:
        name: English (GB)
        icon: gb.png
        model: pc105
        layout: gb
      en_us:
        name: English (US)
        icon: us.png
        model: pc105
        layout: us
      en_mac_ie:
        name: English Mac (IE)
        icon: ie.png
        variant: mac
        model: pc105
        layout: gb
  touchpad:
    enabled: true
    tap_to_click: false
  menu_entries:
    - label: Terminal
      command: x-terminal-emulator
    - label: Web Browser
      command: x-www-browser
    - label: Passwords
      command: flatpak run com.bitwarden.desktop
    - label: File Manager
      command: pcmanfm
    - id: /Debian
      link: true
      separator: true
    - id: client-list-menu
      link: true
      separator: true
    - label: Configuration
      id: /Openbox/Configuration
      separator: true
      submenu:
        - label: Configure
          command: obconf
        - label: Displays
          command: arandr
        - label: Reconfigure
          action_name: Reconfigure
    - label: Quit
      separator: true
      command: oblogout

  panel:
    # L: launcher, T: Taskbar, S: system tray, B: battery, C: clock
    display_items: LTSBC
    shortcuts:
      - /usr/share/applications/tint2-menu.desktop
      - /usr/share/applications/x-www-browser.desktop
      - /var/lib/flatpak/exports/share/applications/com.bitwarden.desktop.desktop
      - /usr/share/applications/x-terminal-emulator.desktop

  rc:
    placement:
      policy: UnderMouse
      monitor: Mouse
    theme:
      font:
        ActiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        InactiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        MenuHeader:
          name: sans
          size: 12
          weight: normal
          slant: normal
        MenuItem:
          name: sans
          size: 12
          weight: normal
          slant: normal
        ActiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
        InactiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
    desktops:
      number: 2
    keybinds:
      - key: W-l
        name: Execute
        command: xscreensaver-command -lock
      - key: W-e
        name: Execute
        command: pcmanfm
      - key: W-m
        name: MoveResizeTo
        x: center
        y: center
      - key: C-A-m
        name: ShowMenu
        menu: root-menu
    mouse:
      screen_edge_warp_time: 0
  autostart:
    - compton -b &
    - xscreensaver -no-splash &
    - tint2 &
    - update-menus &
    - conky &
    - nm-applet &
    - cmst -w 1 -m &
    - redshift-gtk &
    - udiskie --tray &
    - feh --randomize --recursive --bg-center ~/resources/backgrounds/* &
    - ulauncher --hide-window &
    - clipit &
    - carillon &
  launcher:
    hotkey: "<Primary><Alt>space"
  environment:
    lang: en_IE.UTF8
  # any system packages installable via PyPi
  pip_packages:
    - name: carillon
      version: "1.0.2"
      executable: pip3
  # base system packages to get a working, usable OS
  base_packages:
    - gufw
    - ssh-askpass
    - emacs-nox
    - xorg
    - x11-xserver-utils
    - pulseaudio
    - pavucontrol
    - openbox
    - obconf
    - tint2
    - xscreensaver
    - rxvt-unicode
    - scrot
    - pcmanfm
    - fortune-mod
    - conky
    - menu
    - notify-osd
    - libnotify-bin
    - pasystray
    - connman
    - cmst
    - udisks2
    - udiskie
    - compton
    - feh
    - arandr
    - xcal
    - adwaita-icon-theme
  # optional packages required for specific hardware (intended for user override)
  device_packages: []
  static_files:
  - src: sudo.conf
    dest: /etc/sudo.conf
  - src: mimeapps.list
    dest: /usr/share/applications/mimeapps.list
  - src: shortcuts/gufw.desktop
    dest: /usr/share/applications/gufw.desktop
  - src: shortcuts/x-www-browser.desktop
    dest: /usr/share/applications/x-www-browser.desktop
  - src: shortcuts/x-terminal-emulator.desktop
    dest: /usr/share/applications/x-terminal-emulator.desktop
  - src: shortcuts/tint2-menu.desktop
    dest: /usr/share/applications/tint2-menu.desktop
  # fix for borked desktop file in notify-osd package
  - src: shortcuts/notify-osd.desktop
    dest: /etc/xdg/autostart/notify-osd.desktop
