---
openbox:
  xrandr_configuration: ""
  keyboard:
    selected: en_mac_ie
    layouts:
      en_mac_ie:
        name: English Mac (IE)
        icon: ie.png
        variant: mac
        model: pc105
        layout: gb
      en_us:
        name: English (US)
        icon: us.png
        model: pc105
        layout: us
  touchpad:
    enabled: true
    tap_to_click: false
  menu_entries:
    - label: Terminal
      command: x-terminal-emulator
    - label: Web Browser
      command: x-www-browser
    - label: Passwords
      command: password-gorilla
    - label: File Manager
      command: rox
    - label: Browsers
      id: /Personal/Browsers
      separator: true
      submenu:
        - label: Mozilla Firefox
          command: firefox
        - label: Chromium
          command: chromium-browser
        - label: Opera
          command: opera
        - label: Vivaldi
          command: vivaldi
    - label: Configuration
      id: /Personal/Configuration
      separator: true
      submenu:
        - label: Menu Editor
          command: obmenu ~/.config/openbox/app_menu.xml
        - label: Displays
          command: arandr
    - label: Quit
      separator: true
      command: oblogout

  panel:
    # L: launcher, T: Taskbar, S: system tray, B: battery, C: clock
    display_items: LTSBC
    shortcuts:
      - /usr/share/applications/opera.desktop
      - /usr/share/applications/password-gorilla.desktop
      - /usr/share/applications/terminator.desktop

  device_packages: []
  rc:
    placement:
      policy: UnderMouse
      monitor: Mouse
    theme:
      font:
        ActiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        InactiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        MenuHeader:
          name: sans
          size: 12
          weight: normal
          slant: normal
        MenuItem:
          name: sans
          size: 12
          weight: normal
          slant: normal
        ActiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
        InactiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
    desktops:
      number: 2
    keybinds:
      - key: W-l
        name: Execute
        command: xscreensaver-command -lock
      - key: W-e
        name: Execute
        command: rox
        startup_notify: Rox
      - key: W-m
        name: MoveResizeTo
        x: center
        y: center
    mouse:
      screen_edge_warp_time: 0
  autostart:
    - compton -b &
    - xscreensaver -no-splash &
    - tint2 &
    - update-menus &
    - conky &
    - pasystray &
    - nm-applet &
    - redshift-gtk &
    - udiskie --tray &
    - feh --randomize --recursive --bg-center ~/resources/backgrounds/* &
    - ulauncher --hide-window &
    - clipit &
    - carillon &
  launcher:
    hotkey: "<Primary><Alt>space"
  environment:
    lang: en_IE.UTF8
  pip_packages:
    - name: carillon
      version: "1.0.2"
      executable: pip3
  base_packages:
    - python3-pip
  packages:
    - name: emacs24-nox
    - name: xorg
      version: "1:7.7"
    - name: x11-xserver-utils
      version: "7.7*"
    - name: pulseaudio
      version: "1:8.0*"
    - name: pavucontrol
      version: "3.0*"
    - name: openbox
      version: "3.6*"
    - name: obconf
      version: "1:2.0*"
    - name: obmenu
      version: "1.0*"
    - name: tint2
      version: "0.12*"
    - name: xscreensaver
      version: "5.34*"
    - name: rxvt-unicode
      version: "9*"
    - name: scrot
      version: "0.8*"
    - name: rox-filer
      version: "1:2.11*"
    - name: fortune-mod
      version: "1:1.99*"
    - name: conky
      version: "1.10*"
    - name: menu
      version: "2.1*"
    - name: notify-osd
      version: "0.9*"
    - name: libnotify-bin
      version: "0.7*"
    - name: pasystray
      version: "0.4*"
    - name: network-manager
      version: "1.2*"
    - name: network-manager-gnome
      version: "1.2*"
    - name: udisks2
      version: "2.1*"
    - name: udiskie
      version: "1.4*"
    - name: compton
      version: "0.1*"
    - name: feh
      version: "2.14*"
    - name: arandr
      version: "0.1*"
    - name: xcal
      version: "4.1*"
