---
openbox:
  xrandr_configuration: ""
  keyboard:
    selected: en_gb
    layouts:
      en_gb:
        name: English (GB)
        icon: gb.png
        model: pc105
        layout: gb
      en_us:
        name: English (US)
        icon: us.png
        model: pc105
        layout: us
      en_mac_ie:
        name: English Mac (IE)
        icon: ie.png
        variant: mac
        model: pc105
        layout: gb
  touchpad:
    enabled: true
    tap_to_click: false
  menu_entries:
    - label: Terminal
      command: x-terminal-emulator
    - label: Web Browser
      command: x-www-browser
    - label: File Manager
      command: pcmanfm
    - label: Configuration
      id: /Openbox/Configuration
      separator: true
      submenu:
        - label: Openbox
          command: obconf
        - label: Compositor
          command: compton-conf
        - label: Displays
          command: arandr
        - label: Reconfigure
          action_name: Reconfigure
    - label: Logout...
      separator: true
      command: oblogout

  panel:
    width: 100
    height: 24
    icon_size: 22
    max_task_width: 150
    shortcuts:
      - pcmanfm.desktop
      - x-www-browser.desktop
      - x-terminal-emulator.desktop

  rc:
    placement:
      policy: UnderMouse
      monitor: Mouse
    theme:
      font:
        ActiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        InactiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        MenuHeader:
          name: sans
          size: 12
          weight: normal
          slant: normal
        MenuItem:
          name: sans
          size: 12
          weight: normal
          slant: normal
        ActiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
        InactiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
    desktops:
      number: 2
    keybinds:
      - key: XF86MonBrightnessDown
        name: Execute
        command: xbacklight -dec 10
      - key: XF86MonBrightnessUp
        name: Execute
        command: xbacklight -inc 10
      - key: W-l
        name: Execute
        command: xscreensaver-command -lock
      - key: W-e
        name: Execute
        command: pcmanfm
      - key: W-m
        name: MoveResizeTo
        x: center
        y: center
      - key: C-A-h
        name: Execute
        command: x-clipboard-manager
      - key: C-A-m
        name: ShowMenu
        menu: root-menu
    mouse:
      screen_edge_warp_time: 0
  autostart:
    - compton -b &
    - xscreensaver -no-splash &
    - xss-lock -- xscreensaver-command -lock &
    - lxpanel &
    - conky &
    - feh --randomize --recursive --bg-center ~/resources/backgrounds/* &
    - ulauncher --hide-window &
  launcher:
    hotkey: "<Primary><Alt>L"
  environment:
    lang: en_IE.UTF8
  # any system packages installable via PyPi
  pipx_packages: []
    #- name: carillon==1.0.2
  # split by platform
  # * base system packages to get a working, usable OS
  # * common directories used in templates and tasks
  # * autostarting processes
  # * convenient symbolic links
  freebsd:
    icons:
      # Openbox does not use GTK theming so icons are ignored.
      # thus, we use the Adwaita icons directly where needed
      file_manager: /usr/local/share/icons/Adwaita/scalable/apps/system-file-manager-symbolic.svg
      automount: /usr/local/share/icons/Adwaita/scalable/devices/drive-removable-media-symbolic.svg
      terminal: /usr/local/share/icons/Adwaita/scalable/apps/utilities-terminal-symbolic.svg
      web_browser: /usr/local/share/icons/Adwaita/scalable/apps/web-browser-symbolic.svg
    directories:
      home: /usr/home
      system_applications: /usr/local/share/applications
      usr_bin: /usr/local/bin
      lxpanel_common: /usr/local/share/lxpanel
      xdg_config: /usr/local/etc/xdg/autostart
      x11_config: /usr/local/etc/X11
      sudo_config: /usr/local/etc
      policykit_lib: /usr/local/lib/policykit-1
    autostart:
      - clipit &
      - dsbmixer -i &
      - dsbmc -i &
      - dsbbatmon &
      - wpa_gui &
      # redshift is meant to determine location using geoclue but,
      # due to a long-standing bug with redshift (as described
      # https://github.com/jonls/redshift/issues/318) this does not
      # work. There are workarounds (as described in the Arch wiki
      # https://wiki.archlinux.org/title/Redshift#Automatic_location_based_on_GeoClue2)
      # but there's no agent demo easily available for FreeBSD
      # instead, just use a parsed curl call to get a rough location
      - redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') -m randr &
      # TODO: get carillon running again
      - setxkbmap -layout gb
    links:
      - name: x-terminal-emulator
        executable: /usr/local/bin/urxvt
      - name: x-clipboard-manager
        executable: /usr/local/bin/clipit
      - name: x-www-browser
        executable: /usr/local/bin/firefox
    base_packages:
      - name: editors/emacs
      - name: security/openssh-askpass
      - name: x11/arandr
      - name: x11/compton-conf
      - name: x11/lxpanel
      - name: x11/ulauncher
      - name: x11/yad
      - name: x11/xscreensaver
      - name: x11/xorg-minimal
        environment:
          DISABLE_VULNERABILITIES: "yes"
      - name: x11/xorg-apps
      - name: x11/xorg-libraries
      - name: x11/rxvt-unicode
      - name: x11/urxvt-perls
      - name: x11/urxvt-font-size
      - name: x11-themes/adwaita-icon-theme
      - name: x11-fm/pcmanfm
      - name: x11-wm/compton
      - name: x11-wm/openbox
      - name: x11-wm/obconf
      - name: net/wpa_supplicant_gui
      - name: sysutils/conky
      - name: sysutils/dsbmc
      - name: sysutils/dsbbatmon
      - name: sysutils/polkit-qt
      - name: sysutils/htop
      - name: misc/fortune-mod-freebsd-classic
      - name: deskutils/notify-osd
      - name: deskutils/clipit
      - name: devel/libnotify
      - name: devel/dbus
      - name: graphics/scrot
      - name: graphics/feh
      - name: archivers/xarchiver
      - name: audio/dsbmixer
    device_packages: []
    templated_files:
    - src: shortcuts/dsbmc.desktop.j2
      dest: dsbmc.desktop
      directory: system_applications
    static_files: []
  linux:
    icons:
      file_manager: system-file-manager
      automounter: drive-removable-media-usb-pendrive
      terminal: urxvt_48x48.xpm
      web_browser: web-browser
    directories:
      home: /home
      system_applications: /usr/share/applications
      usr_bin: /usr/bin
      lxpanel_common: /usr/share/lxpanel
      xdg_config: /etc/xdg/autostart
      x11_config: /etc/X11
      sudo_config: /etc
      policykit_lib: /usr/lib/policykit-1
    autostart:
      - lxpolkit &
      - update-menus &
      - nm-applet &
      - redshift-gtk &
      - udiskie --tray &
      - diodon &
      - cbatticon &
    alternatives:
      - name: x-terminal-emulator
        executable: /usr/bin/urxvt
        subcommand: set
      - link: /usr/bin/x-www-browser
        name: x-www-browser
        executable: /var/lib/flatpak/exports/bin/org.mozilla.firefox
        priority: "100"
        subcommand: install
      - link: /usr/bin/x-clipboard-manager
        name: x-clipboard-manager
        executable: /usr/bin/diodon
        priority: "100"
        subcommand: install
    base_packages:
      - libcairo2
      - gufw
      - lxpolkit
      - ssh-askpass
      - emacs-nox
      - xorg
      - x11-xserver-utils
      - cbatticon
      - pulseaudio
      - pavucontrol
      - openbox
      - obconf
      - xscreensaver
      - xss-lock
      - rxvt-unicode
      - scrot
      - pcmanfm
      - fortune-mod
      - conky
      - menu
      - notify-osd
      - libnotify-bin
      - pasystray
      - network-manager
      - network-manager-gnome
      - udisks2
      - udiskie
      - compton
      - compton-conf
      - feh
      - arandr
      - yad
      - lxpanel
      - adwaita-icon-theme
      - diodon
      - xarchiver
    # optional packages required for specific hardware (intended for user override)
    device_packages: []
    static_files:
    - src: shortcuts/gufw.desktop
      dest: /usr/share/applications/gufw.desktop
    # fix for borked desktop file in notify-osd package
    - src: shortcuts/notify-osd.desktop
      dest: notify-osd.desktop
      directory: xdg_config
  user_static_files:
  - src: lxpanel/config
    dest: .config/lxpanel/default/config
  - src: lxpanel/launchtaskbar.cfg
    dest: .config/lxpanel/launchtaskbar.cfg
  templated_files:
  - src: sudo.conf.j2
    dest: sudo.conf
    directory: sudo_config
  - src: shortcuts/x-www-browser.desktop.j2
    dest: x-www-browser.desktop
    directory: system_applications
  - src: shortcuts/pcmanfm.desktop.j2
    dest: pcmanfm.desktop
    directory: system_applications
  - src: shortcuts/x-terminal-emulator.desktop.j2
    dest: x-terminal-emulator.desktop
    directory: system_applications
  static_files:
  - src: mimeapps.list
    dest: mimeapps.list
    directory: system_applications
