---
openbox:
  packages:
    - name: xorg
      version: 7.7
    - name: x11-xserver-utils
      version: 7.7
    - name: nvidia-current
    - name: pulseaudio
      version: 8.0
    - name: openbox
      version: 2.0.4
    - name: obconf
      version: 3.6
    - name: obmenu
      version: 1.0