---
openbox:
  xrandr_configuration: ""
  alternatives:
    - command: x-terminal-emulator
      executable: /usr/bin/urxvt
  keyboard:
    selected: en_gb
    layouts:
      en_gb:
        name: English (GB)
        icon: gb.png
        model: pc105
        layout: gb
      en_us:
        name: English (US)
        icon: us.png
        model: pc105
        layout: us
      en_mac_ie:
        name: English Mac (IE)
        icon: ie.png
        variant: mac
        model: pc105
        layout: gb
  touchpad:
    enabled: true
    tap_to_click: false
  menu_entries:
    - label: Terminal
      command: x-terminal-emulator
    - label: Web Browser
      command: x-www-browser
    - label: Passwords
      command: password-gorilla
    - label: File Manager
      command: rox
    - id: /Debian
      link: true
      separator: true
    - id: client-list-menu
      link: true
      separator: true
    - label: Configuration
      id: /Openbox/Configuration
      separator: true
      submenu:
        - label: Configure
          command: obconf
        - label: Menu Editor
          command: obmenu ~/.config/openbox/menu.xml
        - label: Displays
          command: arandr
        - label: Reconfigure
          action_name: Reconfigure
    - label: Quit
      separator: true
      command: oblogout

  panel:
    # L: launcher, T: Taskbar, S: system tray, B: battery, C: clock
    display_items: LTSBC
    shortcuts:
      - /usr/share/applications/tint2-menu.desktop
      - /usr/share/applications/x-www-browser.desktop
      - /usr/share/applications/password-gorilla.desktop
      - /usr/share/applications/x-terminal-emulator.desktop

  device_packages: []
  rc:
    placement:
      policy: UnderMouse
      monitor: Mouse
    theme:
      font:
        ActiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        InactiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        MenuHeader:
          name: sans
          size: 12
          weight: normal
          slant: normal
        MenuItem:
          name: sans
          size: 12
          weight: normal
          slant: normal
        ActiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
        InactiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
    desktops:
      number: 2
    keybinds:
      - key: W-l
        name: Execute
        command: xscreensaver-command -lock
      - key: W-e
        name: Execute
        command: rox
        startup_notify: Rox
      - key: W-m
        name: MoveResizeTo
        x: center
        y: center
      - key: C-A-m
        name: ShowMenu
        menu: root-menu
    mouse:
      screen_edge_warp_time: 0
  autostart:
    - compton -b &
    - xscreensaver -no-splash &
    - tint2 &
    - update-menus &
    - conky &
    - nm-applet &
    - redshift-gtk &
    - udiskie --tray &
    - feh --randomize --recursive --bg-center ~/resources/backgrounds/* &
    - ulauncher --hide-window &
    - clipit &
    - carillon &
  launcher:
    hotkey: "<Primary><Alt>space"
  environment:
    lang: en_IE.UTF8
  pip_packages:
    - name: carillon
      version: "1.0.2"
      executable: pip3
  base_packages:
    - python3-pip
    - gufw
    - geany
    - ssh-askpass
  static_files:
  - src: sudo.conf
    dest: /etc/sudo.conf
  - src: mimeapps.list
    dest: /usr/share/applications/mimeapps.list
  - src: shortcuts/gufw.desktop
    dest: /usr/share/applications/gufw.desktop
  - src: shortcuts/x-www-browser.desktop
    dest: /usr/share/applications/x-www-browser.desktop
  - src: shortcuts/x-terminal-emulator.desktop
    dest: /usr/share/applications/x-terminal-emulator.desktop
  - src: shortcuts/tint2-menu.desktop
    dest: /usr/share/applications/tint2-menu.desktop
  - src: shortcuts/rox-filer.desktop
    dest: /usr/share/applications/rox-filer.desktop
  packages:
    - name: emacs25-nox
    - name: xorg
      version: "1:7.7*"
    - name: x11-xserver-utils
      version: "7.7*"
    - name: pulseaudio
      version: "1:11.1*"
    - name: pavucontrol
      version: "3.0*"
    - name: openbox
      version: "3.6*"
    - name: obconf
      version: "1:2.0*"
    - name: obmenu
      version: "1.0*"
    - name: tint2
      version: "16.2*"
    - name: xscreensaver
      version: "5.36*"
    - name: rxvt-unicode
      version: "9.22*"
    - name: scrot
      version: "0.8*"
    - name: rox-filer
      version: "1:2.11*"
    - name: fortune-mod
      version: "1:1.99*"
    - name: conky
      version: "1.10*"
    - name: menu
      version: "2.1*"
    - name: notify-osd
      version: "0.9*"
    - name: libnotify-bin
      version: "0.7*"
    - name: pasystray
      version: "0.6*"
    - name: network-manager
      version: "1.10*"
    - name: network-manager-gnome
      version: "1.8*"
    - name: udisks2
      version: "2.7*"
    - name: udiskie
      version: "1.7*"
    - name: compton
      version: "0.1*"
    - name: feh
      version: "2.23*"
    - name: arandr
      version: "0.1*"
    - name: xcal
      version: "4.1*"
