---
openbox:
  xrandr_configuration: ""
  alternatives:
    - name: x-terminal-emulator
      executable: /usr/bin/urxvt
      subcommand: set
    - link: /usr/bin/x-www-browser
      name: x-www-browser
      executable: /var/lib/flatpak/exports/bin/org.mozilla.firefox
      priority: "100"
      subcommand: install
  keyboard:
    selected: en_gb
    layouts:
      en_gb:
        name: English (GB)
        icon: gb.png
        model: pc105
        layout: gb
      en_us:
        name: English (US)
        icon: us.png
        model: pc105
        layout: us
      en_mac_ie:
        name: English Mac (IE)
        icon: ie.png
        variant: mac
        model: pc105
        layout: gb
  touchpad:
    enabled: true
    tap_to_click: false
  menu_entries:
    - label: Terminal
      command: x-terminal-emulator
    - label: Web Browser
      command: x-www-browser
    - label: Passwords
      command: /var/lib/flatpak/exports/bin/com.bitwarden.desktop
    - label: File Manager
      command: pcmanfm
    - label: Configuration
      id: /Openbox/Configuration
      separator: true
      submenu:
        - label: Configure
          command: obconf
        - label: Displays
          command: arandr
        - label: Reconfigure
          action_name: Reconfigure
    - label: Logout...
      separator: true
      command: oblogout

  panel:
    width: 100
    height: 24
    icon_size: 22
    max_task_width: 150
    shortcuts:
      - pcmanfm.desktop
      - x-www-browser.desktop
      - com.bitwarden.desktop.desktop
      - lxde-x-terminal-emulator.desktop

  rc:
    placement:
      policy: UnderMouse
      monitor: Mouse
    theme:
      font:
        ActiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        InactiveWindow:
          name: sans
          size: 11
          weight: bold
          slant: normal
        MenuHeader:
          name: sans
          size: 12
          weight: normal
          slant: normal
        MenuItem:
          name: sans
          size: 12
          weight: normal
          slant: normal
        ActiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
        InactiveOnScreenDisplay:
          name: sans
          size: 12
          weight: normal
          slant: normal
    desktops:
      number: 2
    keybinds:
      - key: W-l
        name: Execute
        command: xscreensaver-command -lock
      - key: W-e
        name: Execute
        command: pcmanfm
      - key: W-m
        name: MoveResizeTo
        x: center
        y: center
      - key: C-A-h
        name: Execute
        command: diodon
      - key: C-A-m
        name: ShowMenu
        menu: root-menu
    mouse:
      screen_edge_warp_time: 0
  autostart:
    - lxpolkit &
    - compton -b &
    - xscreensaver -no-splash &
    - lxpanel &
    - update-menus &
    - conky &
    - nm-applet &
    - redshift-gtk &
    - udiskie --tray &
    - feh --randomize --recursive --bg-center ~/resources/backgrounds/* &
    - ulauncher --hide-window &
    - diodon &
    - carillon &
  launcher:
    hotkey: "<Primary><Alt>L"
  environment:
    lang: en_IE.UTF8
  # any system packages installable via PyPi
  pipx_packages: []
    #- name: carillon==1.0.2
  # base system packages to get a working, usable OS
  base_packages:
    - libcairo2
    - gufw
    - lxpolkit
    - ssh-askpass
    - emacs-nox
    - xorg
    - x11-xserver-utils
    - pulseaudio
    - pavucontrol
    - openbox
    - obconf
    - xscreensaver
    - rxvt-unicode
    - scrot
    - pcmanfm
    - fortune-mod
    - conky
    - menu
    - notify-osd
    - libnotify-bin
    - pasystray
    - network-manager
    - network-manager-gnome
    - cmst
    - udisks2
    - udiskie
    - compton
    - feh
    - arandr
    - yad
    - lxpanel
    - adwaita-icon-theme
    - diodon
    - xarchiver
  # optional packages required for specific hardware (intended for user override)
  device_packages: []
  user_static_files:
  - src: lxpanel/config
    dest: .config/lxpanel/default/config
  - src: lxpanel/launchtaskbar.cfg
    dest: .config/lxpanel/launchtaskbar.cfg
  static_files:
  - src: sudo.conf
    dest: /etc/sudo.conf
  - src: mimeapps.list
    dest: /usr/share/applications/mimeapps.list
  - src: shortcuts/gufw.desktop
    dest: /usr/share/applications/gufw.desktop
  - src: shortcuts/x-www-browser.desktop
    dest: /usr/share/applications/x-www-browser.desktop
  - src: shortcuts/x-terminal-emulator.desktop
    dest: /usr/share/applications/x-terminal-emulator.desktop
  # fix for borked desktop file in notify-osd package
  - src: shortcuts/notify-osd.desktop
    dest: /etc/xdg/autostart/notify-osd.desktop
