---
- name: install base packages
  apt: name={{ item.name }}{% if item.version is defined %}={{ item.version }}*{% endif %}
       state=present
  with_items: "{{ base.packages }}"

- name: prep flathub remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: create users
  user: name={{ item.username }} comment="{{ item.name }}"
        password={{ item.password|default(defaults.password) }} shell={{ item.shell }}
  with_items: "{{ users }}"

- name: add polkit rule for mounting volumes
  template: src=mount-internal.rules.j2 dest=/usr/share/polkit-1/rules.d/pcmanfm.mount.rules

- name: enable sudo access for appropriate users
  template: src=sudoers.j2 dest=/etc/sudoers.d/users

- name: update environment with extra paths
  template: src=environment.j2 dest=/etc/environment

- name: set global environment variables for every login
  template: src=pam_env.conf.j2 dest=/etc/security/pam_env.conf

- name: disable system beep
  copy: src=nobeep.conf dest=/etc/modprobe.d/nobeep.conf

- name: configure sysctl settings
  copy: src=sysctl.conf dest=/etc/sysctl.conf
